//
// USERS
//

###
GET http://localhost:8080/academics/api/users
Accept: application/json

###
GET http://localhost:8080/academics/api/users/
Accept: application/json

###
POST http://localhost:8080/academics/api/users
Content-Type: application/json

{
  "username": "eduardo",
  "password": "pass1",
  "tipouser": "LOGISTICA"
}

###
DELETE http://localhost:8080/academics/api/users/1
Content-Type: application/json

//
//ENCOMENDAS
//

###
GET http://localhost:8080/academics/api/encomendas
Accept: application/json

###
GET http://localhost:8080/academics/api/encomendas/10
Accept: application/json

###
GET http://localhost:8080/academics/api/encomendas/cliente/user2
Accept: application/json

###
PUT http://localhost:8080/academics/api/encomendas/10
Content-Type: application/json

{
"cliente" : "user3",
"dataPartida": "2025-01-07 14:43:49.037748",
"dataChegada": "2025-01-08 14:43:49.037748",
"metodoPagamento": "MBWay",
"status": "EmEntrega"


}

###
DELETE http://localhost:8080/academics/api/encomendas/1
Content-Type: application/json



//
// VOLUMES
//

###
GET http://localhost:8080/academics/api/volumes
Accept: application/json

###
GET http://localhost:8080/academics/api/volumes/1
Accept: application/json

###
GET http://localhost:8080/academics/api/volumes/encomenda/1
Accept: application/json

###
POST http://localhost:8080/academics/api/volumes
Content-Type: application/json

{
  "id": "1",
  "idEncomenda": "10"
}

###
DELETE http://localhost:8080/academics/api/volumes/1
Content-Type: application/json

//
// EMBALAGENS
//

###
GET http://localhost:8080/academics/api/embalagens
Accept: application/json

###
GET http://localhost:8080/academics/api/embalagens/1
Accept: application/json

###
GET http://localhost:8080/academics/api/embalagens/encomenda/10
Accept: application/json

###
GET http://localhost:8080/academics/api/embalagens/volume/10-1
Accept: application/json

###
POST http://localhost:8080/academics/api/embalagens
Content-Type: application/json

{
  "id": "1",
  "idVolume": "10",
  "idProduto": "20",
  "quantidade": "5"
}

###
DELETE http://localhost:8080/academics/api/embalagens/1
Content-Type: application/json

//
// PRODUTOS
//

###
GET http://localhost:8080/academics/api/produtos
Accept: application/json

###
GET http://localhost:8080/academics/api/produtos/100
Accept: application/json

###
POST http://localhost:8080/academics/api/produtos
Content-Type: application/json

{
    "id": "1",
    "nome": "Produto1",
    "descricao": "Descricao1",
    "preco": "10"
}

###
PUT http://localhost:8080/academics/api/produtos/1
Content-Type: application/json

{
    "id": "1",
    "nome": "Produto1",
    "descricao": "Descricao1",
    "preco": "20"
}


###
DELETE http://localhost:8080/academics/api/produtos/1
Content-Type: application/json


//
// SENSORES
//

###
GET http://localhost:8080/academics/api/sensors
Accept: application/json

###
GET http://localhost:8080/academics/api/sensors/1
Accept: application/json

###
GET http://localhost:8080/academics/api/sensors/embalagem/2
Accept: application/json

###
POST http://localhost:8080/academics/api/sensors
Content-Type: application/json

{
    "id": "1",
    "tipo": "Temperatura",
    "valor": "20",
    "idVolume": "1"
}


####
//
// REGISTOS
//
GET http://localhost:8080/academics/api/registos
Accept: application/json

####
GET http://localhost:8080/academics/api/registos/3
Accept: application/json
